### ISSUE TITLE
Doesn't show full information in opened tile

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/showcase#14]
![image](https://user-images.githubusercontent.com/35640573/45566783-58bdb900-b860-11e8-8cfd-d22eba262ccf.png)
In this opened tile you can't read all information. Close button doesn't work. You can just scroll up or scroll down but it's close tile.
![image](https://user-images.githubusercontent.com/35640573/45566832-886cc100-b860-11e8-8448-bcc048730645.png)

**Comment by atherdon** [comment]
I pushed some changes, please take a look at my commits in order to understand what i've done.

i think scroll issue is gone, but in order to test it, we should apply some changes in styles. tell me if you want to do it yourself or maybe we can pass styles inside the tile to our markuper. she will happy to help i think

**Comment by atherdon** [comment]
please close this issue if you think it's solved

**Comment by atherdon** [comment]
Julia, this is how content inside the tile looks right now
![react app 1](https://user-images.githubusercontent.com/1469198/45639803-9ff2b680-bab9-11e8-8b6b-8a7d2b09c418.png)

**Comment by vadim9999** [comment]
@atherdon it's doesn't work when you will open Ultimate GroceryList where data is much. Exit button doesn't work. To quite from opened tile you need click F5.
![image](https://user-images.githubusercontent.com/35640573/45819954-52ab5a80-bcee-11e8-9413-83140d8e1797.png)

**Comment by atherdon** [comment]
@vadim9999 Ok, not a problem. Julia will help us with styles, but about "close button issue" I propose you to read setting of plugin that we're using.
because i disable scroll just by changing one argument. maybe someone else will work for close button too. Check it here: https://github.com/GroceriStar/showcase/blob/master/src/App.js#L109

**Comment by akinariobi** [comment]
fixed.
@atherdon should I commit changes to master branch?

**Comment by atherdon** [comment]
@akinariobi yeah, by forking, commiting, and open a pull request that we can merge

**Comment by atherdon** [comment]
@vadim9999 please check an updated version. if it works for you well - please close this task

**Comment by vadim9999** [comment]
It's works very well. We can close this task
